ProyectoIntegradorMvc461/Models/Empresa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProyectoIntegradorMvc461.Models
{
    public class Empresa
    {
        public int id_empresa { get; set; }
        [Required(ErrorMessage = "Debe ingresar Descripcion")]
        public string t_empresa { get; set; }
        [Required(ErrorMessage = "Debe seleccionar Estado")]
        public int f_estado { get; set; }
        public Estado dataEstado { get; set; }
    }
}

ProyectoIntegradorMvc461/Controllers/EmpresaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//Usings
using System.Threading.Tasks;
using ProyectoIntegradorMvc461.Models;
using ProyectoIntegradorMvc461.Filters;

namespace ProyectoIntegradorMvc461.Controllers
{
    public class EmpresaController : Controller
    {
        EmpresaModel model;
        EstadoModel modelEstado;
        public EmpresaController()
        {
            this.model = new EmpresaModel();
            this.modelEstado = new EstadoModel();
        }

        // GET: Empresas
        [AsyncTimeout(1000)]
        [AutorizaUsuario(IdOpcion:2)]   // Filtro 
        public async Task<ActionResult> Index()
        {
            List<Empresa> cList = await model.GetEmpresa();
            return View(cList);
        }

        // GET: Contacts/Details/5
        public async Task<ActionResult> Details(int id)
        {
            Empresa c = await model.GetEmpresaByID(id);
            return View(c);
        }

        // GET: Contacts/Create
        public async Task<ActionResult> Create()
        {
            List<Estado> cListEstado = await this.modelEstado.GetEstado();
            //SelectListItem ObjSelectListItem = new SelectListItem();
            List<SelectListItem> ItemsEstado = cListEstado.ConvertAll(d => {
                return new SelectListItem()
                {
                    Text = d.t_estado.ToString(),
                    Value = d.id_estado.ToString(),
                    Selected = false
                };
            });
            ViewBag.ItemsEstado = ItemsEstado;
            Empresa ObjEntidadNew = new Empresa();
            ObjEntidadNew.id_empresa = 0;
            ObjEntidadNew.f_estado = 1;
            return View(ObjEntidadNew);
        }

        // POST: Contacts/Create
        [HttpPost]
        public async Task<ActionResult> Create(Empresa c)
        {
            try
            {
                await model.AddEmpresa(c);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Contacts/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            // Para cargar Combo de Estado
            List<Estado> cListEstado = await this.modelEstado.GetEstado();
            List<SelectListItem> ItemsEstado = cListEstado.ConvertAll(d => {
                return new SelectListItem()
                {
                    Text = d.t_estado.ToString(),
                    Value = d.id_estado.ToString(),
                    Selected = false
                };
            });
            ViewBag.ItemsEstado = ItemsEstado;
            Empresa c = await model.GetEmpresaByID(id);
            return View(c);
        }

        // POST: Contacts/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(Empresa c)
        {
            try
            {
                await model.EditEmpresa(c);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Contacts/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            await model.DeleteEmpresa(id);
            return RedirectToAction("Index");
        }
    }
}

ProyectoIntegradorMvc461/Views/Empresa/Create.cshtml
@model ProyectoIntegradorMvc461.Models.Empresa

@{
    ViewBag.Title = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<SelectListItem> Items = (List<SelectListItem>)ViewBag.ItemsEstado;
}

<h2>Crear</h2>
<head>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
</head>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Empresa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label class="control-label col-md-2">Id</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.id_empresa, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.id_empresa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Descripcion</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.t_empresa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.t_empresa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @*@Html.LabelFor(model => model.f_estado, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <label class="control-label col-md-2">Estado</label>
        <div class="col-md-10">
            @*fee_earner*@
            @Html.DropDownListFor(model => model.f_estado, new SelectList(Items, "Value", "Text"),
            "Select", new { @class = "form-control", onchange = "selected()", id = "cbo_estado" })
            @Html.ValidationMessageFor(model => model.f_estado, "", new { @class = "text-danger" })
            <span asp-validation-for="cbo_estado" class="text-danger"></span>
        </div>
    </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @*@Html.ActionLink("Regresar a la Lista", "Index")*@
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Empresa")'">Regresar a la Lista</button>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoIntegradorMvc461/Views/Empresa/Details.cshtml
@model ProyectoIntegradorMvc461.Models.Empresa

@{
    ViewBag.Title = "Detalles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalle</h2>

<div>
    <h4>Empresa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @*@Html.DisplayNameFor(model => model.id_empresa)*@
            <label class="control-label col-md-2">Id</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id_empresa)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.t_empresa)*@
            <label class="control-label col-md-2">Descripcion</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.t_empresa)

        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.f_estado)*@
            <label class="control-label col-md-2">Estado</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.f_estado)
        </dd>

    </dl>
</div>
<p>
    @*@Html.ActionLink("Editar", "Edit", new { id = Model.id_empresa }) |
        @Html.ActionLink("Regresar a la Lista", "Index")*@

    <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Edit", "Empresa", new { id = Model.id_empresa })'">Editar</button>
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Empresa")'">Regresar a la Lista</button>

</p>

ProyectoIntegradorMvc461/Views/Empresa/Edit.cshtml
@model ProyectoIntegradorMvc461.Models.Empresa

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<SelectListItem> Items = (List<SelectListItem>)ViewBag.ItemsEstado;
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Empresa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @*@Html.LabelFor(model => model.id_empresa, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <label class="control-label col-md-2">Id</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.id_empresa, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.id_empresa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @*@Html.LabelFor(model => model.t_empresa, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <label class="control-label col-md-2">Descripcion</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.t_empresa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.t_empresa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @*@Html.LabelFor(model => model.f_estado, htmlAttributes: new { @class = "control-label col-md-2" })*@
        @*<label class="control-label col-md-2">Estado</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.f_estado, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.f_estado, "", new { @class = "text-danger" })
        </div>*@
        <label class="control-label col-md-2">Estado</label>
        <div class="col-md-10">
            @*fee_earner*@
            @Html.DropDownListFor(model => model.f_estado, new SelectList(Items, "Value", "Text"),
            "Select", new { @class = "form-control", onchange = "selected()", id = "cbo_estado" })
            @Html.ValidationMessageFor(model => model.f_estado, "", new { @class = "text-danger" })
            <span asp-validation-for="cbo_estado" class="text-danger"></span>
        </div>
    </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Grabar" class="btn btn-success" /> 
            </div>
        </div>
    </div>
}

<div>
    @*@Html.ActionLink("Regresar a la Lista", "Index")*@
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Empresa")'">Regresar a la Lista</button>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoIntegradorMvc461/Views/Empresa/Index.cshtml
@model IEnumerable<ProyectoIntegradorMvc461.Models.Empresa>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    function confirmar() {
        if (confirm("Quieres eliminar el registro?")) {
            document.getElementById("del".value="SI")
        } else {
            document.getElementById("del".value = "NO")
        }
    }
</script>
<h2>Listado de Empresas</h2>
<p>
<button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Create", "Empresa")'">Crear Nuevo</button>
</p>
<table class="table">
    <tr>
        <th>
            Id
        </th>
        <th>
            Descripcion
        </th>
        <th>
            Estado
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id_empresa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.t_empresa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.f_estado)
            </td>
            <td>
                <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Edit", "Empresa", new { id = item.id_empresa })'">Editar</button>
                <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("Details", "Empresa", new { id = item.id_empresa })'">Detalles</button>
                <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Delete", "Empresa", new { id = item.id_empresa })'">Eliminar</button>
            </td>
        </tr>
    }

</table>