ProyectoIntegradorMvc461/Controllers/TicketsPorSistemaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//Usings
using System.Threading.Tasks;
using ProyectoIntegradorMvc461.Models;
using ProyectoIntegradorMvc461.Filters;

namespace ProyectoIntegradorMvc461.Controllers
{
    public class TicketsPorSistemaController : Controller
    {
        
        SistemaModel modelSistema;
        TicketModel modelTicket;
        public TicketsPorSistemaController()
        {
            this.modelSistema = new SistemaModel();
            this.modelTicket = new TicketModel();
        }

        // GET: TicketsPorSistema
        [AsyncTimeout(1000)]
        [AutorizaUsuario(IdOpcion: 7)]   // Filtro 
        public async Task<ActionResult> Index(string cboSistema = "")
        {
            int id_sistema = 0;
            try
            {
                id_sistema = Convert.ToInt32(cboSistema);
            }
            catch (Exception xx)
            {
                id_sistema = 0;
            }

            #region Combo Modulo
            List<Sistema> LstSistema = await this.modelSistema.GetSistema();
            List<SelectListItem> ItemsSistema = LstSistema.ConvertAll(d => {
                return new SelectListItem()
                {
                    Text = d.t_sistema.ToString(),
                    Value = d.id_sistema.ToString(),
                    Selected = false
                };
            });
            #endregion
            ViewBag.ItemsSistema = ItemsSistema;
            List<Ticket> cList;
            if (id_sistema == 0)
            {
                cList = new List<Ticket>();
                cList = await modelTicket.GetTickets();
            }
            else
            {
                cList = new List<Ticket>();
                cList = await modelTicket.GetTicketPorSistema(id_sistema);
            }

            return View(cList);
        }
    }
}

ProyectoIntegradorMvc461/Views/TicketsPorSistema/Index.cshtml
@model IEnumerable<ProyectoIntegradorMvc461.Models.Ticket>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<SelectListItem> ItemsSistema = (List<SelectListItem>)ViewBag.ItemsSistema;
}

<h2>Tickets por Sistema</h2>

@using (Html.BeginForm("Index", "TicketsPorSistema", FormMethod.Post))
{
    <div>
        @Html.DropDownList("cboSistema", ItemsSistema, "Seleccionar", new { @class = "form-control" })
        <button type="submit" class="btn btn-default">Buscar</button>
    </div>
}

@if (Model != null)
{
    <table class="table">
        <tr>
            <th>
                Id.Ticket
            </th>
            <th>
                Empresa
            </th>
            <th>
                Usuario
            </th>
            <th>
                Sistema
            </th>
            <th>
                Modulo
            </th>
            <th>
                Tipo de Ticket
            </th>
            <th>
                Estado de Ticket
            </th>
            <th>
                Observacion
            </th>
            <th>
                Informe de Solución
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id_ticket)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.t_empresa)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.c_usuario)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.t_sistema)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.t_modulo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.t_tipo_ticket)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.t_estado_ticket)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.t_observacion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.t_informe_solucion)
                </td>
                <td>
                    @*<button type="button" class="btn btn-info" onclick="location.href='@Url.Action("Editar", "TicketResolutor", new { id = item.id_ticket})'">Atender Ticket</button>*@
                </td>
            </tr>
        }

    </table>
}