ProyectoIntegradorMvc461/Controllers/TicketResolutorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
// Usings
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Mvc;
using ProyectoIntegradorMvc461.Models;
using System.Net.Http;
using Newtonsoft.Json;
using System.Threading.Tasks;
using System.Net.Http.Headers;
using ProyectoIntegradorMvc461.Filters;

namespace ProyectoIntegradorMvc461.Controllers
{
    public class TicketResolutorController : Controller
    {
        public int pid_usuario { get; set; }
        public int pid_empresa { get; set; }
        TicketModel modelTicket;
        EstadoModel modelEstado;
        EmpresaModel modelEmpresa;
        UsuarioModel modelUsuario;
        SistemaModel modelSistema;
        ModuloModel modelModulo;
        Tipo_TicketModel modelTipo_Ticket;
        Estado_TicketModel modelEstado_Ticket;
        // 
        Usuario_EmpresaModel modelUsuario_Empresa;
        Usuario_EmpresasModel modelUsuario_Empresas;

        //string Url = "https://localhost:44396/";
        private String UriApi;
        private readonly IConfiguration _configuration;
        MediaTypeWithQualityHeaderValue mediaheader;
        public TicketResolutorController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public TicketResolutorController()
        {
            this.modelTicket = new TicketModel();
            this.modelEstado = new EstadoModel();
            this.modelEmpresa = new EmpresaModel();
            this.modelUsuario = new UsuarioModel();
            this.modelSistema = new SistemaModel();
            this.modelModulo = new ModuloModel();
            this.modelTipo_Ticket = new Tipo_TicketModel();
            this.modelEstado_Ticket = new Estado_TicketModel();
            //
            this.modelUsuario_Empresa = new Usuario_EmpresaModel();
            this.modelUsuario_Empresas = new Usuario_EmpresasModel();

            this.UriApi = "https://localhost:44396/"; // Local API
            this.mediaheader = new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json");
        }
        //public async Task<IActionResult> Index()
        // GET: Sistemas
        [AsyncTimeout(1000)]
        [AutorizaUsuario(IdOpcion: 14)]   // Filtro 
        public async Task<ActionResult> Index()
        {
            List<Ticket> TicketsAll = new List<Ticket>();
            using (HttpClient client = new HttpClient())
            {
                String petition = "api/Ticket";
                client.BaseAddress = new Uri(this.UriApi);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(mediaheader);
                HttpResponseMessage respuesta = await client.GetAsync(petition);
                if (respuesta.IsSuccessStatusCode)
                {
                    var _clientResponse = respuesta.Content.ReadAsStringAsync().Result;
                    //Deserializar el Api y Almacenar los datos
                    TicketsAll = JsonConvert.DeserializeObject<List<Ticket>>(_clientResponse);
                }
            }
            return View(TicketsAll);  //(IActionResult)
        }

        // GET: Contacts/Edit/5
        public async Task<ActionResult> Editar(int id)
        {
            #region Combo Estado
            List<Estado> LstEstado = await this.modelEstado.GetEstado();
            List<SelectListItem> ItemsEstado = LstEstado.ConvertAll(d => {
                return new SelectListItem()
                {
                    Text = d.t_estado.ToString(),
                    Value = d.id_estado.ToString(),
                    Selected = false
                };
            });
            #endregion
            #region Combo Empresa
            List<Empresa> LstEmpresa = await this.modelEmpresa.GetEmpresa();
            List<SelectListItem> ItemsEmpresa = LstEmpresa.ConvertAll(d => {
                return new SelectListItem()
                {
                    Text = d.t_empresa.ToString(),
                    Value = d.id_empresa.ToString(),
                    Selected = false
                };
            });
            #endregion
            #region Combo Usuario
            List<Usuario> LstUsuario = await this.modelUsuario.GetUsuario();
            List<SelectListItem> ItemsUsuario = LstUsuario.ConvertAll(d => {
                return new SelectListItem()
                {
                    Text = d.c_usuario.ToString(),
                    Value = d.id_usuario.ToString(),
                    Selected = false
                };
            });
            #endregion
            #region Combo Sistema
            List<Sistema> LstSistema = await this.modelSistema.GetSistema();
            List<SelectListItem> ItemsSistema = LstSistema.ConvertAll(d => {
                return new SelectListItem()
                {
                    Text = d.t_sistema.ToString(),
                    Value = d.id_sistema.ToString(),
                    Selected = false
                };
            });
            #endregion
            #region Combo Modulo
            List<Modulo> LstModulo = await this.modelModulo.GetModulo();
            List<SelectListItem> ItemsModulo = LstModulo.ConvertAll(d => {
                return new SelectListItem()
                {
                    Text = d.t_modulo.ToString(),
                    Value = d.id_modulo.ToString(),
                    Selected = false
                };
            });
            #endregion
            #region Combo Tipo_Ticket
            List<Tipo_Ticket> LstTipo_Ticket = await this.modelTipo_Ticket.GetTipo_Ticket();
            List<SelectListItem> ItemsTipo_Ticket = LstTipo_Ticket.ConvertAll(d => {
                return new SelectListItem()
                {
                    Text = d.t_tipo_ticket.ToString(),
                    Value = d.id_tipo_ticket.ToString(),
                    Selected = false
                };
            });
            #endregion
            #region Combo Estado_Ticket
            List<Estado_Ticket> LstEstado_Ticket = await this.modelEstado_Ticket.GetEstado_Ticket();
            List<SelectListItem> ItemsEstado_Ticket = LstEstado_Ticket.ConvertAll(d => {
                return new SelectListItem()
                {
                    Text = d.t_estado_ticket.ToString(),
                    Value = d.id_estado_ticket.ToString(),
                    Selected = false
                };
            });
            #endregion

            Ticket ObjTicket = await this.modelTicket.GetTicketByID(id);
            ViewBag.ItemsEstado = ItemsEstado;
            ViewBag.ItemsEmpresa = ItemsEmpresa;
            ViewBag.ItemsUsuario = ItemsUsuario;
            ViewBag.ItemsSistema = ItemsSistema;
            ViewBag.ItemsModulo = ItemsModulo;
            ViewBag.ItemsTipo_Ticket = ItemsTipo_Ticket;
            ViewBag.ItemsEstado_Ticket = ItemsEstado_Ticket;
            //ObjTicket
            //Usuario_Empresa c = await modelUsuario_Empresa.GetUsuario_EmpresaByID(id);
            return View(ObjTicket);
        }

        // POST: Contacts/Edit/5
        [HttpPost]
        public async Task<ActionResult> Editar(Ticket c)
        {
            try
            {
                await modelTicket.EditTicket(c);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Contacts/Create
        public async Task<ActionResult> Crear()
        {
            //Response.Redirect("https://localhost:44384/Mensajes");

            //Response.Redirect(this.UriApi + "Mensajes");
            #region Combo Estado
            List<Estado> cListEstado = await this.modelEstado.GetEstado();
            List<SelectListItem> ItemsEstado = cListEstado.ConvertAll(d => {
                return new SelectListItem()
                {
                    Text = d.t_estado.ToString(),
                    Value = d.id_estado.ToString(),
                    Selected = false
                };
            });
            #endregion
            #region Combo Empresa
            List<Empresa> LstEmpresa = await this.modelEmpresa.GetEmpresa();
            List<SelectListItem> ItemsEmpresa = LstEmpresa.ConvertAll(d => {
                return new SelectListItem()
                {
                    Text = d.t_empresa.ToString(),
                    Value = d.id_empresa.ToString(),
                    Selected = false
                };
            });
            #endregion
            #region Combo Usuario
            List<Usuario> LstUsuario = await this.modelUsuario.GetUsuario();
            List<SelectListItem> ItemsUsuario = LstUsuario.ConvertAll(d => {
                return new SelectListItem()
                {
                    Text = d.c_usuario.ToString(),
                    Value = d.id_usuario.ToString(),
                    Selected = false
                };
            });
            #endregion
            #region Combo Sistema
            List<Sistema> LstSistema = await this.modelSistema.GetSistema();
            List<SelectListItem> ItemsSistema = LstSistema.ConvertAll(d => {
                return new SelectListItem()
                {
                    Text = d.t_sistema.ToString(),
                    Value = d.id_sistema.ToString(),
                    Selected = false
                };
            });
            #endregion
            #region Combo Modulo
            List<Modulo> LstModulo = await this.modelModulo.GetModulo();
            List<SelectListItem> ItemsModulo = LstModulo.ConvertAll(d => {
                return new SelectListItem()
                {
                    Text = d.t_modulo.ToString(),
                    Value = d.id_modulo.ToString(),
                    Selected = false
                };
            });
            #endregion
            #region Combo Tipo_Ticket

ProyectoIntegradorMvc461/Views/TicketResolutor/Editar.cshtml
@model ProyectoIntegradorMvc461.Models.Ticket

@{
    ViewBag.Title = "Atencion de Ticket";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<SelectListItem> Items = (List<SelectListItem>)ViewBag.ItemsEstado;
    List<SelectListItem> ItemsEmpresa = (List<SelectListItem>)ViewBag.ItemsEmpresa;
    List<SelectListItem> ItemsUsuario = (List<SelectListItem>)ViewBag.ItemsUsuario;
    List<SelectListItem> ItemsSistema = (List<SelectListItem>)ViewBag.ItemsSistema;
    List<SelectListItem> ItemsModulo = (List<SelectListItem>)ViewBag.ItemsModulo;
    List<SelectListItem> ItemsTipo_Ticket = (List<SelectListItem>)ViewBag.ItemsTipo_Ticket;
    List<SelectListItem> ItemsEstado_Ticket = (List<SelectListItem>)ViewBag.ItemsEstado_Ticket;
}

<h2>Atencion de Ticket</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Atender Ticket</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        <label class="control-label col-md-2">Id Ticket</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.id_ticket, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.id_ticket, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @*@Html.LabelFor(model => model.f_estado, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <label class="control-label col-md-2">Empresa</label>
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.id_empresa, new SelectList(ItemsEmpresa, "Value", "Text"),
            "Select", new { @class = "form-control", @disabled = "disabled", onchange = "selected()", id = "cbo_empresa" })
            @Html.ValidationMessageFor(model => model.id_empresa, "", new { @class = "text-danger" })
            <span asp-validation-for="cbo_empresa" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        @*@Html.LabelFor(model => model.f_estado, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <label class="control-label col-md-2">Usuario</label>
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.id_usuario, new SelectList(ItemsUsuario, "Value", "Text"),
            "Select", new { @class = "form-control", @disabled = "disabled", onchange = "selected()", id = "cbo_usuario" })
            @Html.ValidationMessageFor(model => model.id_usuario, "", new { @class = "text-danger" })
            <span asp-validation-for="cbo_usuario" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        @*@Html.LabelFor(model => model.f_estado, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <label class="control-label col-md-2">Sistema</label>
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.id_sistema, new SelectList(ItemsSistema, "Value", "Text"),
            "Select", new { @class = "form-control", @disabled = "disabled", onchange = "selected()", id = "cbo_sistema" })
            @Html.ValidationMessageFor(model => model.id_sistema, "", new { @class = "text-danger" })
            <span asp-validation-for="cbo_sistema" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        @*@Html.LabelFor(model => model.f_estado, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <label class="control-label col-md-2">Modulo</label>
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.id_modulo, new SelectList(ItemsModulo, "Value", "Text"),
            "Select", new { @class = "form-control", @disabled = "disabled", onchange = "selected()", id = "cbo_modulo" })
            @Html.ValidationMessageFor(model => model.id_modulo, "", new { @class = "text-danger" })
            <span asp-validation-for="cbo_modulo" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        @*@Html.LabelFor(model => model.f_estado, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <label class="control-label col-md-2">Tipo de Ticket</label>
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.id_tipo_ticket, new SelectList(ItemsTipo_Ticket, "Value", "Text"),
            "Select", new { @class = "form-control", @disabled = "disabled", onchange = "selected()", id = "cbo_Tipo_Ticket" })
            @Html.ValidationMessageFor(model => model.id_modulo, "", new { @class = "text-danger" })
            <span asp-validation-for="cbo_Tipo_Ticket" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        @*@Html.LabelFor(model => model.f_estado, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <label class="control-label col-md-2">Estado de Ticket</label>
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.id_estado_ticket, new SelectList(ItemsEstado_Ticket, "Value", "Text"),
            "Select", new { @class = "form-control", onchange = "selected()", id = "cbo_Estado_Ticket" })
            @Html.ValidationMessageFor(model => model.id_estado_ticket, "", new { @class = "text-danger" })
            <span asp-validation-for="cbo_Estado_Ticket" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        @*@Html.LabelFor(model => model.t_observacion, htmlAttributes: new { @class = "control-label col-md-2", @disabled = "disabled"})*@
        <label class="control-label col-md-2">Observacion</label>
        <div class="col-md-10">
            @*col-md-10*@
            @*@Html.EditorFor(model => model.t_observacion, new { htmlAttributes = new { @class = "form-control", rows = "20" } })*@
            @Html.EditorFor(model => model.t_observacion, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled", rows = "7" } })

            @Html.ValidationMessageFor(model => model.t_observacion, "", new { @class = "text-danger" })
            @*<textarea class="span6" rows="3" placeholder="What's up?" required></textarea>*@
        </div>
    </div>
    <div class="form-group">
        @*@Html.LabelFor(model => model.t_observacion, htmlAttributes: new { @class = "control-label col-md-2", @disabled = "disabled"})*@
        <label class="control-label col-md-2">Informe de Solucion</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.t_informe_solucion, new { htmlAttributes = new { @class = "form-control", rows = "7" } })
            @Html.ValidationMessageFor(model => model.t_informe_solucion, "", new { @class = "text-danger" })
            @*<textarea class="span6" rows="3" placeholder="What's up?" required></textarea>*@
        </div>
    </div>
    <div class="form-group">
        @*@Html.LabelFor(model => model.f_estado, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <label class="control-label col-md-2">Estado</label>
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.f_estado, new SelectList(Items, "Value", "Text"),
            "Select", new { @class = "form-control", onchange = "selected()", id = "cbo_estado" })
            @Html.ValidationMessageFor(model => model.f_estado, "", new { @class = "text-danger" })
            <span asp-validation-for="cbo_estado" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Grabar" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "TicketResolutor")'">Regresar a la Lista</button>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoIntegradorMvc461/Views/TicketResolutor/Index.cshtml
@model IEnumerable<ProyectoIntegradorMvc461.Models.Ticket>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Atencion de Tickets</h2>

<p>
    @*@Html.ActionLink("Crear Nuevo Ticket", "Crear")*@
</p>
<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.id_empresa)*@
            Id.Ticket
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.t_empresa)*@
            Empresa
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.id_usuario)
        </th>*@
        <th>
            @*@Html.DisplayNameFor(model => model.c_usuario)*@
            Usuario
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.id_sistema)
        </th>*@
        <th>
            @*@Html.DisplayNameFor(model => model.t_sistema)*@
            Sistema
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.id_modulo)
        </th>*@
        <th>
            @*@Html.DisplayNameFor(model => model.t_modulo)*@
            Modulo
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.id_tipo_ticket)
        </th>*@
        <th>
            @*@Html.DisplayNameFor(model => model.t_tipo_ticket)*@
            Tipo de Ticket
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.id_estado_ticket)
        </th>*@
        <th>
            @*@Html.DisplayNameFor(model => model.t_estado_ticket)*@
            Estado de Ticket
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.t_observacion)*@
            Observacion
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.t_observacion)*@
            Informe de Solución
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.f_estado)
        </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    @*<td>
            @Html.DisplayFor(modelItem => item.id_empresa)
        </td>*@
    <td>
        @Html.DisplayFor(modelItem => item.id_ticket)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.t_empresa)
    </td>
    @*<td>
            @Html.DisplayFor(modelItem => item.id_usuario)
        </td>*@
    <td>
        @Html.DisplayFor(modelItem => item.c_usuario)
    </td>
    @*<td>
        @Html.DisplayFor(modelItem => item.id_sistema)
        </td>*@
    <td>
        @Html.DisplayFor(modelItem => item.t_sistema)
    </td>
    @*<td>
        @Html.DisplayFor(modelItem => item.id_modulo)
        </td>*@
    <td>
        @Html.DisplayFor(modelItem => item.t_modulo)
    </td>
    @*<td>
            @Html.DisplayFor(modelItem => item.id_tipo_ticket)
        </td>*@
    <td>
        @Html.DisplayFor(modelItem => item.t_tipo_ticket)
    </td>
    @*<td>
            @Html.DisplayFor(modelItem => item.id_estado_ticket)
        </td>*@
    <td>
        @Html.DisplayFor(modelItem => item.t_estado_ticket)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.t_observacion)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.t_informe_solucion)
    </td>

    @*<td>
            @Html.DisplayFor(modelItem => item.f_estado)
        </td>*@
    <td>
        <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("Editar", "TicketResolutor", new { id = item.id_ticket})'">Atender Ticket</button>

        @*<button type="button" class="btn btn-info" onclick="location.href='@Url.Action("Detalle", "Usuario", new { id = item.id_ticket})'">Detalles</button>*@
        @*<button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Eliminar", "Usuario", new { id = item.id_ticket})'">Eliminar</button>*@

    </td>
</tr>
    }

</table>