ProyectoIntegradorMvc461/Models/Sistema.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProyectoIntegradorMvc461.Models
{
    public class Sistema
    {
        public int id_sistema { get; set; }
        [Required(ErrorMessage = "Debe ingresar Descripcion")]
        public string t_sistema { get; set; }
        [Required(ErrorMessage = "Debe seleccionar Estado")]
        public int f_estado { get; set; }
    }
}

ProyectoIntegradorMvc461/Controllers/SistemaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//Usings
using System.Threading.Tasks;
using ProyectoIntegradorMvc461.Models;
using ProyectoIntegradorMvc461.Filters;

namespace ProyectoIntegradorMvc461.Controllers
{
    public class SistemaController : Controller
    {
        SistemaModel model;
        EstadoModel modelEstado;
        public SistemaController()
        {
            this.model = new SistemaModel();
            this.modelEstado = new EstadoModel();
        }

        // GET: Sistemas
        [AsyncTimeout(1000)]
        [AutorizaUsuario(IdOpcion: 3)]   // Filtro 
        public async Task<ActionResult> Index()
        {
            List<Sistema> cList = await model.GetSistema();
            return View(cList);
        }

        // GET: Contacts/Details/5
        public async Task<ActionResult> Detalle(int id)
        {
            Sistema c = await model.GetSistemaByID(id);
            return View(c);
        }

        // GET: Contacts/Create
        public async Task<ActionResult> Crear()
        {         
            List<Estado> cListEstado = await this.modelEstado.GetEstado();
            //SelectListItem ObjSelectListItem = new SelectListItem();
            List<SelectListItem> ItemsEstado = cListEstado.ConvertAll(d => {
                return new SelectListItem()
                {
                    Text = d.t_estado.ToString(),
                    Value = d.id_estado.ToString(),
                    Selected = false
                };
            });
            ViewBag.ItemsEstado = ItemsEstado;
            Sistema ObjEntidadNew = new Sistema();
            ObjEntidadNew.id_sistema = 0;
            ObjEntidadNew.f_estado = 1;
            return View(ObjEntidadNew);
            //return View();
        }

        // POST: Contacts/Create
        [HttpPost]
        public async Task<ActionResult> Crear(Sistema c)
        {
            try
            {
                await model.AddSistema(c);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Contacts/Edit/5
        public async Task<ActionResult> Editar(int id)
        {
            // Para cargar Combo de Estado
            List<Estado> cListEstado = await this.modelEstado.GetEstado();
            List<SelectListItem> ItemsEstado = cListEstado.ConvertAll(d => {
                return new SelectListItem()
                {
                    Text = d.t_estado.ToString(),
                    Value = d.id_estado.ToString(),
                    Selected = false
                };
            });
            ViewBag.ItemsEstado = ItemsEstado;
            Sistema c = await model.GetSistemaByID(id);
            return View(c);
        }

        // POST: Contacts/Edit/5
        [HttpPost]
        public async Task<ActionResult> Editar(Sistema c)
        {
            try
            {
                await model.EditSistema(c);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Contacts/Delete/5
        public async Task<ActionResult> Eliminar(int id)
        {
            await model.DeleteSistema(id);
            return RedirectToAction("Index");
        }
    }
}

ProyectoIntegradorMvc461/Views/Sistema/Crear.cshtml
@model ProyectoIntegradorMvc461.Models.Sistema

@{
    ViewBag.Title = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<SelectListItem> Items = (List<SelectListItem>)ViewBag.ItemsEstado;
}

<h2>Crear</h2>
<head>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
</head>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Sistema</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Id</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_sistema, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.id_sistema, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Descripcion</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.t_sistema, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.t_sistema, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.f_estado, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Estado</label>
            <div class="col-md-10">
                @*fee_earner*@
                @Html.DropDownListFor(model => model.f_estado, new SelectList(Items, "Value", "Text"),
                "Select", new { @class = "form-control", onchange = "selected()", id = "cbo_estado" })
                @Html.ValidationMessageFor(model => model.f_estado, "", new { @class = "text-danger" })
                <span asp-validation-for="cbo_estado" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @*@Html.ActionLink("Regresar a la Lista", "Index")*@
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Sistema")'">Regresar a la Lista</button>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoIntegradorMvc461/Views/Sistema/Detalle.cshtml
@model ProyectoIntegradorMvc461.Models.Sistema

@{
    ViewBag.Title = "Detalle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalle</h2>

<div>
    <h4>Sistema</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @*@Html.DisplayNameFor(model => model.id_sistema)*@
            <label class="control-label col-md-2">Id</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id_sistema)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.t_sistema)*@
            <label class="control-label col-md-2">Descripcion</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.t_sistema)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.f_estado)*@
            <label class="control-label col-md-2">Estado</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.f_estado)
        </dd>

    </dl>
</div>
<p>
    @*@Html.ActionLink("Editar", "Editar", new { /* id = Model.PrimaryKey */ }) |
        @Html.ActionLink("Retornar a la Lista", "Index")*@

    <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Editar", "Sistema", new { id = Model.id_sistema })'">Editar</button>
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Sistema")'">Regresar a la Lista</button>
</p>

ProyectoIntegradorMvc461/Views/Sistema/Editar.cshtml
@model ProyectoIntegradorMvc461.Models.Sistema

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<SelectListItem> Items = (List<SelectListItem>)ViewBag.ItemsEstado;
}


<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Sistema</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @*@Html.LabelFor(model => model.id_sistema, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Id</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_sistema, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.id_sistema, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.t_sistema, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Descripcion</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.t_sistema, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.t_sistema, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Estado</label>
            <div class="col-md-10">
                @*fee_earner*@
                @Html.DropDownListFor(model => model.f_estado, new SelectList(Items, "Value", "Text"),
                "Select", new { @class = "form-control", onchange = "selected()", id = "cbo_estado" })
                @Html.ValidationMessageFor(model => model.f_estado, "", new { @class = "text-danger" })
                <span asp-validation-for="cbo_estado" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Grabar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @*@Html.ActionLink("Regresar a la Lista", "Index")*@
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "Sistema")'">Regresar a la Lista</button>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoIntegradorMvc461/Views/Sistema/Index.cshtml
@model IEnumerable<ProyectoIntegradorMvc461.Models.Sistema>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Listado de Sistemas</h2>

<p>
    @*@Html.ActionLink("Nuevo", "Crear")*@
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Crear", "Sistema")'">Crear Nuevo</button>
</p>
<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.id_sistema)*@
            <label class="control-label col-md-2">Id</label>
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.t_sistema)*@
            <label class="control-label col-md-2">Descripcion</label>
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.f_estado)*@
            <label class="control-label col-md-2">Estado</label>
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.id_sistema)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.t_sistema)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.f_estado)
        </td>
        <td>
            @*@Html.ActionLink("Editar", "Edit", new { id = item.id_sistema }) |
            @Html.ActionLink("Detalle", "Details", new { id = item.id_sistema }) |
            @Html.ActionLink("Eliminar", "Delete", new { id = item.id_sistema })*@
            <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Editar", "Sistema", new { id = item.id_sistema})'">Editar</button>
            <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("Detalle", "Sistema", new { id = item.id_sistema})'">Detalles</button>
            <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Eliminar", "Sistema", new { id = item.id_sistema })'">Eliminar</button>
        </td>
    </tr>
}

</table>